### ISSUE TITLE
Better `Vary` support with multiple responses cached with different "vary"-values.

### ISSUE THREAD

**Issue by Kevinrob** [Kevinrob/guzzle-cache-middleware#35]

**Comment by wheelsandcogs** [comment]
Hi, as I understand it from the code, all requests with the same method / uri share the same cache key? 

Is there any progress towards supporting separate caching for varied headers?

**Comment by Kevinrob** [comment]
Hi, yes it's correct. No, there isn't any progress about that.
I review and accept PR if you have some time to do that 👍

**Comment by wheelsandcogs** [comment]
Just had a look at doing this, but it's proving difficult without a major refactor of the caching layer.

Currently if the vary headers in the request differ from those in the response cache, a new request is made and the new response replaces the existing cache for that URL.

To handle separate caching per vary headers, we need to keep track of the vary headers for each URL, so that we can generate the correct cache key using a hash of the URL + vary headers (or similar).

As it stands, `CacheStorageInterface::save()` only allows persistence of type `CacheEntry`, (which requires `Request` & `Response` objects) so unfortunately we can't do something simple like:

```
// in class PrivateCacheStrategy
private function saveVaryHeadersForUrl($url, array $headers)
{
    $key = 'vary_headers.'.sha1($url);
    $this->storage->save($key, $headers);
}

private function fetchVaryHeadersForUrl($url)
{
    $key = 'vary_headers.'.sha1($url);
    return $this->storage->fetch($key);
}
```

to store & retrieve the vary headers.

**Comment by wheelsandcogs** [comment]
A less invasive way would be to store the original response under `hash('sha256', $request->getMethod().$request->getUri());`  as is done currently, but also create a separate cache key using the response vary headers, and store the response again under the new key.

This would remove the need to refactor the caching layer to support array storage, but it seems like a lot of cache overhead when all that is needed is the list of vary headers.

**Comment by wheelsandcogs** [comment]
PR added here: https://github.com/Kevinrob/guzzle-cache-middleware/pull/75

**Comment by Kevinrob** [comment]
Thank you for looking at this issue! I will do my best for reviewing your PR as soon as possible. 😃
